# Generated by Django 6.0.7 on 2026-07-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
