# Generated by Django 6.0.7 on 2026-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
